### ISSUE TITLE
Duplicate windows process on wox restart

### ISSUE THREAD

**Issue by rickmed** [Wox-launcher/Wox#414]
When restarting wox using wox command, the previous OS process does not terminate.

build 1.2.605, win10x64,.

**Comment by bao-qian** [comment]
Can't reproduce. Screenshot of task manager please.

**Comment by rickmed** [comment]
![screenclip](https://cloud.githubusercontent.com/assets/7104786/11484274/5c81f33a-977f-11e5-96e0-448588b1a66d.png)
![2](https://cloud.githubusercontent.com/assets/7104786/11484271/5c7c1794-977f-11e5-8d5a-9a533de84394.png)
![3](https://cloud.githubusercontent.com/assets/7104786/11484272/5c7c5ee8-977f-11e5-8c4e-758b189b6406.png)
![4](https://cloud.githubusercontent.com/assets/7104786/11484273/5c7f402c-977f-11e5-997c-74969f5e498e.png)

**Comment by bao-qian** [comment]
As you see, finally the first Wox instance is closed.

**Comment by rickmed** [comment]
No. 
When wox is opened (on the background) there is 1 process (first screenshot).
When wox is brought to focus, the process disappears (2nd screenshot).
When wox is restarted (and opened on the background), 1 additional process is added (2 in total). 3rd screenshot.
When wox is brought to focus this time, it's process disappears, but as the first one did not terminate, it stays opened. (4th screenshot).

**Comment by bao-qian** [comment]
The first did terminated. Please use **Details** tab to checkout process ID.
They will have different process ID.
The reason there are 2 process is because the second one is trying to kill the first one.

**Comment by rickmed** [comment]
Correct. Sorry. What I meant was that there are 2 Wox processes (not 2 exact same wox processes) when restarting wox. 
So, when you restart wox and there are 2 processes after a while, it means the 2nd one did not succeed in killing the first one? For example, if I restart wox a few times (with a few minutes in between), there are a few wox processes running. That should not happen, right? I'm a newbie so excuse me if I'm way out of line...

**Comment by bao-qian** [comment]
This won't happen.

> when you restart wox and there are 2 processes after a while, it means the 2nd one did not succeed in killing the first one

It means the second is currently **killing** the fist one.

**Comment by rickmed** [comment]
But there are still 2 processes after 30 minutes of restarting wox...

**Comment by bao-qian** [comment]
So what you mean is the time span between the third screenshot and fourth screenshot is 30 minutes?

**Comment by rickmed** [comment]
Yes. Wox never kills the first process when restarting (I checked after 30 minutes or so)

(Although, the screenshots may be a bit confusing since they where on the background processes in the processes tab, my mistake)

**Comment by bao-qian** [comment]
Strange. Could you provide two screenshot for detail tab along with time like this:
![sample](http://i.imgur.com/Pe0n792.png)
fist one for the beginning of two process. second one for one process has been killed.

Also please provide logs from `Wox\Logs`. (delete existing log files before experiment)

**Comment by rickmed** [comment]
Just before pressing enter...
![2015-11-30_17-36-47](https://cloud.githubusercontent.com/assets/7104786/11486177/8276bfbc-9789-11e5-9eeb-1be78b8eb75d.png)
after 5 minutes...
![2015-11-30_17-41-21](https://cloud.githubusercontent.com/assets/7104786/11486188/a10c3cf4-9789-11e5-96f0-b8374567bbea.png)

Logs

2015-11-30 17:42:47.9356|WARN|Wox.Infrastructure.Logger.Log|parse plugin C:\Users\rickm\Wox\Plugins\Close Screen-17bf1545-1591-4a5e-909a-88d3490c24db\plugin.json failed: didn't find config file.
2015-11-30 17:42:47.9946|WARN|Wox.Infrastructure.Logger.Log|parse plugin C:\Users\rickm\Wox\Plugins\Remove USB-485c68de-919e-4cb6-b0b2-945ee8f7b6a0\plugin.json failed: didn't find config file.
2015-11-30 17:42:47.9946|WARN|Wox.Infrastructure.Logger.Log|parse plugin C:\Users\rickm\Wox\Plugins\Wox.Plugin.SimpleClock-93c92e2f-c5e4-47d5-9fde-7876b811b2d7\plugin.json failed: didn't find config file.
2015-11-30 17:42:48.3379|INFO|Wox.Infrastructure.Logger.Log|Preload 288 programs from cache
2015-11-30 17:43:02.4496|WARN|Wox.Infrastructure.Logger.Log|parse plugin C:\Users\rickm\Wox\Plugins\Close Screen-17bf1545-1591-4a5e-909a-88d3490c24db\plugin.json failed: didn't find config file.
2015-11-30 17:43:02.5176|WARN|Wox.Infrastructure.Logger.Log|parse plugin C:\Users\rickm\Wox\Plugins\Remove USB-485c68de-919e-4cb6-b0b2-945ee8f7b6a0\plugin.json failed: didn't find config file.
2015-11-30 17:43:02.5246|WARN|Wox.Infrastructure.Logger.Log|parse plugin C:\Users\rickm\Wox\Plugins\Wox.Plugin.SimpleClock-93c92e2f-c5e4-47d5-9fde-7876b811b2d7\plugin.json failed: didn't find config file.
2015-11-30 17:43:02.9649|INFO|Wox.Infrastructure.Logger.Log|Preload 288 programs from cache

**Comment by bao-qian** [comment]
Could you find these  files?

```
C:\Users\rickm\Wox\Plugins\Close Screen-17bf1545-1591-4a5e-909a-88d3490c24db\plugin.json
C:\Users\rickm\Wox\Plugins\Remove USB-485c68de-919e-4cb6-b0b2-945ee8f7b6a0\plugin.json
C:\Users\rickm\Wox\Plugins\Wox.Plugin.SimpleClock-93c92e2f-c5e4-47d5-9fde-7876b811b2d7\plugin.json 
```

Try delete these folders:

```
C:\Users\rickm\Wox\Plugins\Close Screen-17bf1545-1591-4a5e-909a-88d3490c24db
C:\Users\rickm\Wox\Plugins\Remove USB-485c68de-919e-4cb6-b0b2-945ee8f7b6a0
C:\Users\rickm\Wox\Plugins\Wox.Plugin.SimpleClock-93c92e2f-c5e4-47d5-9fde-7876b811b2d7
```

**Comment by rickmed** [comment]
did not work.

logs
2015-11-30 17:55:23.9810|INFO|Wox.Infrastructure.Logger.Log|Preload 288 programs from cache

**Comment by bao-qian** [comment]
There are two process on your screenshot, 4836 and 2696. Which has been killed?

**Comment by rickmed** [comment]
what do you mean? 
Neither one. That is the problem.

**Comment by bao-qian** [comment]
so if you restart again, there will be three process?

**Comment by rickmed** [comment]
Yes.

**Comment by bao-qian** [comment]
to be honest. I don't have any clue and can't reproduce it.

**Comment by bao-qian** [comment]
Some thoughts:
1. will restart help?
2. Why this screenshot shows that there is only one Wox process?
![screenshot](https://cloud.githubusercontent.com/assets/7104786/11484273/5c7f402c-977f-11e5-997c-74969f5e498e.png)
3. when you type <kbd>Alt</kbd> <kbd>Tab</kbd>, which instance of Wox will be invoked? (you can check this by using "go to details" in processes tab, and check the process id)

**Comment by rickmed** [comment]
1) what do you mean?
2) Because I made a mistake of taking a screenshot of the background processes part of task manager's processes tab. So when an app gains focus, it disappears from the background processes list. So there were 2 wox processes at the time, 1 with focus and 1 running in the background (You can confirm that in my last posted screenshot of the details tab).
3) I did 3 tests. In all of them the wox instance that opened on alt tab was the originally created instance (NOT the one created on restart).

BTW, the exit close wox command does not work properly (maybe it is related). It closes the window (can't be summoned with alt tab) and eliminates the tray icon but the process remains running in the background.

**Comment by bao-qian** [comment]
Yeah, the close wox command is related. restart will start second first, and call close command for the first instance. Could you use close command properly with [v1.2beta](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta)?

**Comment by rickmed** [comment]
Yes. It works. Although, it kills it abruptly (the "wox stopped working, windows is checking for a solution..." window comes up).
Restart works just as exit (closes wox abruptly)

**Comment by bao-qian** [comment]
I know, the restart of 1.2 is not work. I think I fixed this (at least for my self), but it seems like it brings some other (unreproducible) issues.

**Comment by lances101** [comment]
I used to have the problems with exiting  that @ricmed205 is describing, but now it's alright (since the restart update). 

It will be hard to debug what is happening in your system, @ricmed205, because I cannot reproduce this on any of the five machines that I have access to

**Comment by rickmed** [comment]
Maybe it's a win10 permissions issue. Tried the suggestions in the issues list and others without success...

**Comment by bao-qian** [comment]
I'm using windows 10 too. This is not a windows 10 permission issue.

**Comment by DaveyD** [comment]
I can confirm that this is still an issue
Using the restart command, Wox keeps on duplicating the process
Each time you run restart, it creates a new process and older processes do not get closed.

This might also have to do with issue #498

**Comment by bao-qian** [comment]
@DaveyD 

since you already have the latest version, then
1. did you remove all plugins?
2. please provide logs from `Wox\Logs`. (delete old logs before try to restart)

**Comment by DaveyD** [comment]
Ok, first, can you tell me:
1. What is the correct way to install updates? (With the last one I just created a new folder with the new files and ran it from there)
2. If what I did in #1 is ok, what do I do about old plugins that I installed? Can I just copy over those folders?
3. What about settings?

Thanks

**Comment by DaveyD** [comment]
CORRECTION!
Both problems are solved..... sort of
After a lot of testing I realized that it was a plugin that was causing these issues
I had 2 plugins installed
1. Doc plugin
2. Clipboard plugin

After removing the clipboard plugin, everything works perfectly! Exit and Restart!
(Just to confirm, I also tried removing Doc plugin and leaving only Clipboard plugin, it still caused the issues.)

So, in short:
1. Issue #498 can remain closed
2. Maybe this issue can be closed?
3. We need to create a new issue by the clipboard plugin

**Comment by bao-qian** [comment]
Thanks for testing.
Actually **you inspired me** the root cause for this issue maybe is plugin.
This issue can be remain opened until we add some mechanize force restart wox even if some plugin prevent it.

**Comment by bao-qian** [comment]
@rickmed did you installed `clipboard` plugin? Could you try again by remove that plugin folder?

**Comment by bao-qian** [comment]
@DaveyD override is just fine. we will add one click update mechanize soon.

**Comment by DaveyD** [comment]
@happlebao Both enhancements sound great!
Thanks

**Comment by bao-qian** [comment]
wox should gracefully restart now, try again.
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.0
