### ISSUE TITLE
Lock to primary display

### ISSUE THREAD

**Issue by staff0rd** [Wox-launcher/Wox#510]
I notice that Wox will open on the display that my mouse pointer is on.

Is it possible to make it only open on my primary display?

**Comment by lances101** [comment]
There is an option in the general tab for Wox to remember it's position. Try enabling that.

**Comment by staff0rd** [comment]
Sorry, I should have mentioned I had tried that.  It would seem that that option does not control which display Wox appears on, rather, what position Wox was in last on that display.  With the option enabled, Wox still appears on whatever display the mouse is present.

**Comment by lances101** [comment]
Confirmed. This is weird though. It respects the stored top coordinates, but not the left ones.

**Comment by staff0rd** [comment]
Installing vs community 2015 now, i'll give it a shot if you like...

**Comment by lances101** [comment]
Found it. 

~~When the ViewModel was added, the committer did not notice the fact that every time Wox was to be shown it checked if the Remember Last Location setting is enabled or not. Now it does not. Wox always sticks to its last location~~ 

**Edit**: nope. The latest build does not seem to have the symptom. Only the release version. This needs some digging and I do not have enough time right now :(

**Comment by bao-qian** [comment]
@staff0rd which version?

**Comment by staff0rd** [comment]
Sorry, I wasn't sure this was a bug or not so I didn't try dev.  It's release 1.2.0.

**Edit**: Am getting latest build now from AppVeyor

**Comment by bao-qian** [comment]
@staff0rd not v1.2.0-beta.2 right? then try [it](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta.2)....
If it still fails, then try [latest build](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.758/artifacts)

**Comment by staff0rd** [comment]
@happlebao it was v.1.2.0-beta.2

I'm trying latest build now.  Where does Wox store custom added web search entries?  Installing latest build in a different path wiped my entries...

**Comment by staff0rd** [comment]
Issue fixed in v1.2.758.

**Comment by bao-qian** [comment]
@staff0rd sorry for that, `Wox\Config\settings_plugin_websearch`. just copy and rename it, the structure should be same.

**Comment by bao-qian** [comment]
Confirmed.
Seems the calculation didn't count the start X and start Y.

**Comment by bao-qian** [comment]
@staff0rd @lances101 
Hi, try again using build [1.2.778](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.778/artifacts).
Reopen it if problem still exist.
