### ISSUE TITLE
[Build 1.2.882]Suggestions on default web search url and bugs report

### ISSUE THREAD

**Issue by iF2007** [Wox-launcher/Wox#582]
## Web search URL suggestions

It's better to use **https** instead of http, although some of these search providers use HSTS.
## Bugs (Discovered on Windows 10 x64, Build 10586.218)
- Can't exit Wox correctly (need kill process)
- Settings are not saved after restart (VERY ANNOYING!).

I'm a heavy user and Wox is very useful and powerful. Hope bugs can be fixed before final release.
Cheers

**Comment by bao-qian** [comment]
The settings should be fixed today( in my time zone of course )
What do you actually mean by can't exit wox ? Type exit and press enter or alt+ f4?

**Comment by bao-qian** [comment]
Thanks for your support!

**Comment by bao-qian** [comment]
temp fix for settings would be exit manually (type exit and enter)

**Comment by iF2007** [comment]
By can't exit Wox I mean when right click on tray icon, the process still exists and so does the tray icon, but I can't use wox interface anymore. For now, I can only terminate using process killing.
I also tried using compatibility mode (Windows 7) and the problem still exists.

Thanks.

**Comment by iF2007** [comment]
@happlebao I shared my revision of %appdata%\Roaming\Wox\Settings\Plugins\Wox.Plugin.WebSearch\Settings.json [here](https://gist.github.com/iF2007/a7f1cadaa517a9a6e1eade0d54f811fa).  
Some revisions including:
1. All default search urls are using **https** instead of http (if possible).
2. Add 2 more search option: Google scholar and Baidu.

Feel free to use or not to.

Thanks.

**Comment by bao-qian** [comment]
thanks for report
the settings should be fixed in this build: https://ci.appveyor.com/project/happlebao/wox/build/1.2.892/artifacts

**Comment by iF2007** [comment]
@happlebao I tried build 1.2.892. It seems that settings can be saved correctly.
Meanwhile, Wox can only exit by terminate the process. Enter `Exit' and enter won't work for me.

Cheers.

**Comment by bao-qian** [comment]
@iF2007 paste your log here 
`%APPDATA%\Wox\Logs`

**Comment by bao-qian** [comment]
baidu is added：
https://ci.appveyor.com/project/happlebao/wox/build/1.2.894/artifacts

**Comment by iF2007** [comment]
@happlebao 
I can't find older logs but only yesterday's. Check it out [here](http://pastebin.com/QphAB3ub)

Thanks.

**Comment by bao-qian** [comment]
@iF2007 delete `Wox.Plugin.Timestamp` directory should solve your problem.

**Comment by bao-qian** [comment]
reopen it if you can't solve it.
