### ISSUE TITLE
[Wox.Plugin.WebSearch] 2 bugs

### ISSUE THREAD

**Issue by fylimas** [Wox-launcher/Wox#922]
## English

Try search existing issues before you open new one
1. Wox version 1.3.183
2. Steps to **reproduce** the bug:
   ![1](https://cloud.githubusercontent.com/assets/17979090/17687526/61a60324-63a8-11e6-8d2a-404328448d09.png)
   -select the icon for an item in WebSearch
   ![2](https://cloud.githubusercontent.com/assets/17979090/17687528/65dc4886-63a8-11e6-83b3-40564d3e1f2a.png)
   ![3](https://cloud.githubusercontent.com/assets/17979090/17687532/6bc449a6-63a8-11e6-8f91-8620f531f71b.png)
   -save change (the logical behind "the hotkey has been already assigned!" should be changed to "the hotkey has been already assigned **to another item**!", because if the hotkey is assigned to this self item, then it is not changed, it should not be considered as "has been already assigned" and popup a message! (This bug **has been fixed** by Megasware128))
   ![4](https://cloud.githubusercontent.com/assets/17979090/17687537/772671a2-63a8-11e6-916b-41f69a6cbd0d.png)
   -anyway, save the selection of icon by changing hotkey "l" to "l0"(any hotkey that has not been assigned) then change back to "l"
   ![5](https://cloud.githubusercontent.com/assets/17979090/17687540/80d7037e-63a8-11e6-8864-e7721e4535ec.png)
   ![6](https://cloud.githubusercontent.com/assets/17979090/17687562/b4938e08-63a8-11e6-98b5-c8f1f900b998.png)
   -restart Wox
   
   -all the icon of each item in the list of "Web Search" change back to "web_search.png" (**One Bug Left**)
   ![7](https://cloud.githubusercontent.com/assets/17979090/17687569/c50c946e-63a8-11e6-8924-caaf7b1e71e7.png)
   ![8](https://cloud.githubusercontent.com/assets/17979090/17687572/c7307896-63a8-11e6-910d-1778b86cd382.png)
3. Windows version: win10/10586
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：
   ![1](https://cloud.githubusercontent.com/assets/17979090/17687526/61a60324-63a8-11e6-8d2a-404328448d09.png)
   -编辑链接，并选择图标
   ![2](https://cloud.githubusercontent.com/assets/17979090/17687528/65dc4886-63a8-11e6-83b3-40564d3e1f2a.png)
   ![3](https://cloud.githubusercontent.com/assets/17979090/17687532/6bc449a6-63a8-11e6-8f91-8620f531f71b.png)
   -保存更改 (如果没有更改 热键 的话，会弹出热键已被占用的对话框，使得保存不能成功。这是一个bug，因为这个热键仅仅给了这个链接使用，而没有给其他链接使用，不应该弹出对话框。(这个bug已经由Megasware128修复))
   ![4](https://cloud.githubusercontent.com/assets/17979090/17687537/772671a2-63a8-11e6-916b-41f69a6cbd0d.png)
   -anyway, save the selection of icon by changing hotkey "l" to "l0"(any hotkey that has not been assigned) then change back to "l"
   ![5](https://cloud.githubusercontent.com/assets/17979090/17687540/80d7037e-63a8-11e6-8864-e7721e4535ec.png)
   ![6](https://cloud.githubusercontent.com/assets/17979090/17687562/b4938e08-63a8-11e6-98b5-c8f1f900b998.png)
   -重启wox
   
   -所有链接的图标又变成"web_search.png"了（尚未有确定的修复消息）
   ![7](https://cloud.githubusercontent.com/assets/17979090/17687569/c50c946e-63a8-11e6-8924-caaf7b1e71e7.png)
   ![8](https://cloud.githubusercontent.com/assets/17979090/17687572/c7307896-63a8-11e6-910d-1778b86cd382.png)
3. Windows 版本：10/10586
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
   [2016-08-16.txt](https://github.com/Wox-launcher/Wox/files/419513/2016-08-16.txt)
6. 截图 （可选）：

**Comment by Megasware128** [comment]
"the hotkey has been already assigned!" has been fixed in #856

**Comment by fylimas** [comment]
well done. I did not know that. Now there should be ONE bug left here.

**Comment by Lewis-Liu** [comment]
我也遇到了这个问题，改了图标后，重启wox，自动恢复默认。

**Comment by Phecda** [comment]
而且自定义的搜索也不起作用了。
Customized web searches become unavailable neither.

**Comment by jupitia** [comment]
This bug still remains at least in version 1.3.183 for me
And every time import images into the directory under Roaming folder, all previous setting will gone after restart, in which case one will have to reset every shortcut manually again, and worse, encountering the mentioned bug every single time.

**Comment by fylimas** [comment]
The newest version may save some changes when the program is quite/exit manually.
However this may cause some unintentional bugs such as unsaved changes and "already assign hotkeys" (though it is not assigned to any item) due to that sometimes the Wox program will exits (not manually) with unknown reasons.

I am not an expert and not sure if my guess is right or not.
May the changes can be saved immediately? 

Best regards.

**Comment by bao-qian** [comment]
this bug seems fixed long ago, anybody wants to test the new build?
https://ci.appveyor.com/project/happlebao/wox/build/1.3.344

**Comment by bao-qian** [comment]
reopen if the issue still exist

**Comment by fylimas** [comment]
I am busy about Fund now. I will give it a try ASAP.

Thanks for your great work!

**Comment by ybbqg** [comment]
Wox-1.3.357 同样问题，新触发关键字已经被指派给其他插件了，
标题完全可以省略

**Comment by bao-qian** [comment]
@ybbqg log 和截图

**Comment by ybbqg** [comment]
![default](https://cloud.githubusercontent.com/assets/1767875/23537223/9be5bff8-0005-11e7-914a-15c47150347a.png)

**Comment by bao-qian** [comment]
@ybbqg **log** 和截图

**Comment by fylimas** [comment]
I do not know why the problem still exists for you @ybbqg .
However, it works fine on my computer. (新版本在我机器上运行良好。)

You may want to uninstall wox AND delete files: C:\Users\XXX\AppData\Roaming\Wox.
Then reinstall the newest version of Wox to see if the problem still exists.
(你可以试试：卸载Wox，删除文件C:\Users\XXX\AppData\Roaming\Wox；然后重新安装Wox，看看问题是不是仍然存在)
